name: pastelog
description: PasteLog is a simple, fast, and powerful pastebin. It is powered by
  firebase in the backend. It allows you to publish your logs, and access them
  from anywhere and any device via a unique link.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.4
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^3.0.4
  google_fonts: ^2.3.2
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.8
  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  logger: ^1.1.0
  shared_preferences: ^2.0.13

flutter:
  uses-material-design: true
