name: pastelog
description: PasteLog is a simple, fast, and powerful pastebin. It is powered by
  firebase in the backend. It allows you to publish your logs, and access them
  from anywhere and any device via a unique link.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_vector: ^0.2.0
  cloud_firestore: ^4.17.4
  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.23
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  rive: ^0.13.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  logger: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
