name: pastelog
description: PasteLog is a simple, fast, and powerful pastebin. It is powered by
  firebase in the backend. It allows you to publish your logs, and access them
  from anywhere and any device via a unique link.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_vector: ^0.2.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^7.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.4
  json_serializable: ^6.7.1
  logger: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
