// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_utH-muJpF3GZYWtpEiRuwVcbOLxol2U',
    appId: '1:790912897367:web:dbe7bb555038e48a6fee12',
    messagingSenderId: '790912897367',
    projectId: 'pastelog-id',
    authDomain: 'pastelog-id.firebaseapp.com',
    storageBucket: 'pastelog-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEcsdpy2W_Ib35tkgXvM8E31taqK9O4Ok',
    appId: '1:790912897367:android:adf558552e717a7b6fee12',
    messagingSenderId: '790912897367',
    projectId: 'pastelog-id',
    storageBucket: 'pastelog-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0Gaeh_gMwdfD2CD22SHYsePOYAlxK3M',
    appId: '1:790912897367:ios:0ea554e18b75614f6fee12',
    messagingSenderId: '790912897367',
    projectId: 'pastelog-id',
    storageBucket: 'pastelog-id.appspot.com',
    iosClientId: '790912897367-deuel19ba9pr0kf380n25e6vqgulkkkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe0Gaeh_gMwdfD2CD22SHYsePOYAlxK3M',
    appId: '1:790912897367:ios:0ea554e18b75614f6fee12',
    messagingSenderId: '790912897367',
    projectId: 'pastelog-id',
    storageBucket: 'pastelog-id.appspot.com',
    iosClientId: '790912897367-deuel19ba9pr0kf380n25e6vqgulkkkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCreate',
  );
}
