name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Generate the .env file with required environment variables
      - name: Create .env file
        run: echo "${{ secrets.PASTELOG_ENV }}" > .env

      # Install dependencies and build the project
      - run: npm ci && npm run build

      # # Deploy to Firebase Hosting
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASTELOG_ID }}"
      #     channelId: live
      #     projectId: pastelog-id
      #   env:
      #     FIREBASE_CLI_PREVIEWS: hostingchannels
